name: Assign Issue Number

on:
  issues:
    types: [opened]

jobs:
  assign-issue-number:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Set issue prefix
        run: echo "ISSUE_PREFIX=TEST$(date +'%y')" >> $GITHUB_ENV


      - name: Assign custom issue number
        uses: SHIV5T3R/Issuer@main
        with:
          APP_ID: ${{ secrets.ISSUE_GEN_APP_ID }}
          APP_KEY: ${{ secrets.ISSUE_GEN_APP_KEY }}
          ISSUE_PREFIX: ${{ env.ISSUE_PREFIX }}
          ISSUE_COUNTER: ${{ vars.ISSUE_NUMBER }}
          ISSUE_COUNTER_VAR: "ISSUE_NUMBER"
          ORG_NAME: "sanger"
